# https://github.com/benadida/helios-server/blob/master/INSTALL.md
# set env vars:  POSTGRES_PASSWORD, SERVER_URL, SECRET_KEY, RABBITMQ_DEFAULT_PASS, DEFAULT_FROM_EMAIL, MAIN_LOGO_URL, 
# EMAIL_HOST, AUTH_LDAP_SERVER_URI, AUTH_LDAP_BASE, AUTH_LDAP_BIND_DN, AUTH_LDAP_BIND_PASSWORD, HELIOS_BASEDIR
version: '3'

services:
  rabbitmq:
    image: rabbitmq:3.10.6-management-alpine
    container_name: rabbitmq
    restart: unless-stopped
    volumes:
      - rabbitmq_conf:/etc/rabbitmq
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE:-secret_cookie}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-admin}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-admin}
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 30s
      timeout: 20s
      retries: 5
      
  postgres:
    image: postgres:15.4-alpine
    container_name: postgres
    environment:
      - POSTGRES_DB=helios
      - POSTGRES_USER=helios
      - POSTGRES_INITDB_ARGS="--auth-host=md5"
      - POSTGRES_PASSWORD 
    restart: unless-stopped
    volumes:   
      - pg_data:/var/lib/postgresql/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    healthcheck:
      test: ["CMD", "sh", "-c", "pg_isready -U postgres"]
      interval: 30s
      timeout: 5s
      retries: 5
    networks:
      - postgresql
      
  web:
    image: python:3.6
    container_name: helios
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_proxy
      - traefik.http.services.guac.loadbalancer.server.port=8000
      - traefik.http.routers.guac.rule=Host(`${SERVER_URL}`)
      - traefik.http.routers.guac.tls.certresolver=letsencrypt
      - traefik.frontend.entryPoints=http,https
    working_dir: /app
    environment:
      - TZ
      - LANGUAGE_CODE
      - DEBUG=0
      - SECRET_KEY
      - ALLOWED_HOSTS=${DOMAIN_NAME}
      - URL_HOST=/
      - SSL=1
      - EMAIL_HOST
      - EMAIL_PORT
      - ADMIN_EMAIL
      - ADMIN_NAME
      - HELIOS_ADMIN_ONLY="True"
      - SHOW_LOGIN_OPTIONS=False
      - MEDIA_ROOT
      - HELP_EMAIL_ADDRESS=${EMAIL_CONTACT}
      - CELERY_BROKER_URL=amqp://admin:${RABBITMQ_DEFAULT_PASS}@rabbitmq:5672/0
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}/${POSTGRES_DB}
      - DEFAULT_FROM_EMAIL
      - DEFAULT_FROM_NAME
      - SITE_TITLE
      - MAIN_LOGO_URL
      - FOOTER_LOGO_URL
      - WELCOME_MESSAGE
      - AUTH_DEFAULT_SYSTEM
      - AUTH_ENABLED_AUTH_SYSTEMS=password,ldap
      - AUTH_LDAP_SERVER_URI
      - AUTH_LDAP_BASE
      - AUTH_LDAP_BIND_DN
      - AUTH_LDAP_BIND_PASSWORD
    volumes:
      - media:${MEDIA_ROOT}
      - ${FAVICON}:/app/server_ui/media/favicon.ico
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - proxy_default
      - postgresql 
    depends_on:
      postgres:
        condition: service_healthy
          
networks:
  proxy_default:
    external: true
  postgresql:
    driver: bridge
    ipam:
     config:
       - subnet: 192.168.101.0/24

volumes:
  media:
    name: media
    driver_opts:
       type: none
       device: ${HELIOS_BASEDIR}/media
       o: bind
  rabbitmq-data:
    name: rabbitmq-data
    driver_opts:
       type: none
       device: ${HELIOS_BASEDIR}/rabbitmq-data
       o: bind
  rabbitmq-conf:
    name: rabbitmq-conf
    driver_opts:
       type: none
       device: ${HELIOS_BASEDIR}/rabbitmq-conf
  pg_data:
    name: pg_data
    driver_opts:
       type: none
       device: ${HELIOS_BASEDIR}/pg_data
